# -*- coding: utf-8 -*-
from django.conf import settings

DEFAULT_KEY_LENGTH = 16
KEY_LENGTH = getattr(settings, 'KEY_LENGTH', DEFAULT_KEY_LENGTH)

DEFAULT_SECRET_LENGTH = 32
SECRET_LENGTH = getattr(settings, 'DEFAULT_SECRET_LENGTH', DEFAULT_SECRET_LENGTH)

DEFAULT_VERIFIER_LENGTH = 6
VERIFIER_LENGTH = getattr(settings, 'DEFAULT_VERIFIER_LENGTH', DEFAULT_VERIFIER_LENGTH)

DEFAULT_SIGNIN_ATTEMPTS_COUNT = 5
SIGNIN_ATTEMPTS_COUNT = getattr(settings, 'SIGNIN_ATTEMPTS_COUNT', DEFAULT_SIGNIN_ATTEMPTS_COUNT)

DEFAULT_SIGNIN_BRUTE_FORCE_PROTECTION_PAUSE = 3 * 24 * 60 * 60 * 1000
SIGNIN_BRUTE_FORCE_PROTECTION_PAUSE = getattr(settings, 'SIGNIN_BRUTE_FORCE_PROTECTION_PAUSE', DEFAULT_SIGNIN_BRUTE_FORCE_PROTECTION_PAUSE)